# Use postgres/example user/password credentials
version: '3.1'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgresuser
      POSTGRES_DB: servdb

    